name: Ezra's Project Site
path: https://kenhung.github.io/Ezra
ezra:
  version: 2.0
  integrity: o+tOlLJ3SV6TdIQMMdApSiZfENYb4Lpo27Fr9/cequ1Fwc54te0NjMMJNYNKCFX6
  integrity_sc: 0DpMjaD+jT4owj9CVgXZwXKhcIdX884HkH+ix5Ns6mCkZo4wbpWIoP3bx4qOWgy8