name: Ezra's Project Site
path: https://kenhung.github.io/Ezra
ezra:
  version: 2.1
  integrity: W/oS16oOYqVIrVYUfW8vYY7thfW9zGvuLlZni7kcLEsRiu1iM5jU/knDQHur7J7O
  integrity_sc: 4cQUJCRGMyOx3isLWW6nSm7Al6g55DAokHdbMx5xdl00Bnw+2khp/1RpYTZdZe/Y
