name: Ezra's Project Site
path: https://kenhung.github.io/Ezra
ezra:
  version: 2.2
  integrity: nd9OSZaJr/i3p+qvoHgPqzE/X0H6ymwsAPPX0Hazu11sgVHD1Qh2KJU4H+Q1ZFui
  integrity_sc: AQNNAJSs9uIkjLFOyquhCXXLCKnN8Mxs/WlImaALpUjYKFQ/16h4a13MgGqG3o7L
